# This file is usually generated by alembic init, but we are creating it manually for the "base" import
# to ensure all models are imported when autogenerating migrations.

from app.db.session import Base
from app.db.models import Document, Version, Execution
